package main

import (
	b64 "encoding/base64"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func main() {

	out, err := os.Create("embedded.go")
	if err != nil {
		log.Fatal(err)
	}
	_, _ = out.Write([]byte("// Code generated by ./embedded/generate.go. DO NOT EDIT\n"))
	_, _ = out.Write([]byte(fmt.Sprintf("// generated: %s\n\n", time.Now().Format(time.RFC1123Z))))
	_, _ = out.Write([]byte("package main\n\n"))
	_, _ = out.Write([]byte("import \"html/template\"\n\n"))

	// html template
	html, _ := ioutil.ReadFile("./embedded/template.html")
	_, _ = out.Write([]byte("var htmlTemplate = template.Must(template.New(\"tmp\").Parse(`\n"))
	_, _ = out.Write(html)
	_, _ = out.Write([]byte("`))\n\n"))

	dirs := []string{"css", "script", "font"}

	_, _ = out.Write([]byte("var assets = map[string]string {\n"))

	for _, d := range dirs {
		_ = filepath.Walk(fmt.Sprintf("./embedded/%s", d), func(path string, info os.FileInfo, err error) error {
			if info.IsDir() {
				return nil
			}
			data, err := ioutil.ReadFile(path)
			if err != nil {
				return err
			}
			vName := fmt.Sprintf("%s_%s", d, strings.Replace(filepath.Base(path), ".", "_", 1))
			enc := b64.StdEncoding.EncodeToString(data)
			_, _ = out.Write([]byte(fmt.Sprintf(" `%s`: `", vName)))
			_, _ = out.Write([]byte(enc))
			_, _ = out.Write([]byte("`,\n"))
			return nil
		})
	}
	_, _ = out.Write([]byte("}\n\n"))
}
