project_name: mdsync
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      pre: go generate
archives:
  - format_overrides:
    - goos: windows
      format: zip
nfpms:
  - id: dev.rverst.mdync
    maintainer: Robert Verst <info@rverst.dev>
    description: Markdown html renderer with auto reload.
    homepage: https://github.com/rverst/mdsync
    license: MIT
    formats:
    - deb
    - rpm
    - apk
